package constant

// Thông báo lỗi dùng chung trong API response.
const (
	MsgUnauthorized            = "Không có quyền truy cập"
	MsgAccessDenied            = "Không có quyền truy cập"
	MsgInternalServerError     = "Lỗi máy chủ nội bộ"
	MsgMissingAccessToken      = "Thiếu token truy cập"
	MsgTokenExpired            = "Token đã hết hạn"
	MsgInvalidToken            = "Token không hợp lệ"
	MsgTokenRevoked            = "Token đã bị thu hồi"
	MsgMissingRole             = "Thiếu vai trò người dùng"
	MsgInvalidRole             = "Vai trò không hợp lệ"
	MsgInsufficientPermissions = "Không đủ quyền thực hiện thao tác"
	MsgMissingRefreshToken     = "Thiếu token làm mới"
	MsgInvalidUserID           = "ID người dùng không hợp lệ"
	MsgInvalidPatientID        = "ID bệnh nhân không hợp lệ"
	MsgInvalidDoctorID         = "ID bác sĩ không hợp lệ"
	MsgInvalidPrescriptionID   = "ID đơn thuốc không hợp lệ"
	MsgInvalidFromDate         = "Ngày bắt đầu không hợp lệ, dùng định dạng YYYY-MM-DD"
	MsgInvalidToDate           = "Ngày kết thúc không hợp lệ, dùng định dạng YYYY-MM-DD"
	MsgInvalidDateRange        = "Ngày kết thúc phải sau hoặc bằng ngày bắt đầu"
	MsgInvalidConversationID   = "ID cuộc trò chuyện không hợp lệ"
	MsgInvalidSessionID        = "ID phiên không hợp lệ"
	MsgInvalidCursor           = "Con trỏ phân trang không hợp lệ"
	MsgConversationIDRequired  = "conversationId hoặc patientId là bắt buộc"
	MsgAlertNotFound           = "Không tìm thấy cảnh báo"
	MsgPrescriptionNotFound    = "Không tìm thấy đơn thuốc"
	MsgAppointmentNotFound     = "Không tìm thấy lịch tái khám"
	MsgNotificationNotFound    = "Không tìm thấy thông báo"
	MsgOnlyDoctorOrNurse       = "Chỉ bác sĩ hoặc điều dưỡng mới xem được danh sách bệnh nhân được phân công"
	MsgOnlyPatient             = "Chỉ bệnh nhân mới có quyền thực hiện thao tác này"
	MsgMissingAssignmentID     = "Thiếu ID phân công"
	MsgFailedFetchActivityLogs = "Không thể lấy nhật ký hoạt động"
	MsgFailedCountActivityLogs = "Không thể đếm nhật ký hoạt động"
	MsgFailedFetchStatistics   = "Không thể lấy thống kê"
	MsgOnlyImageFilesAllowed   = "Chỉ cho phép tải lên file ảnh"
	MsgCannotOpenFile          = "Không thể mở file"
	MsgUploadFailed            = "Tải lên thất bại"
	MsgFailedSaveAvatar        = "Không thể lưu ảnh đại diện"
)
